apiVersion: v1
kind: Pod
metadata:
  name: mifastapi-pod
  labels:
    app: mifastapi
spec:
  containers:
    - name: mifastapi
      image: jose9496/mifastapi:latest
      ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: redis
spec:
  containers:
    - name: redis
      image: redis:latest
      ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: mifastapi-svc
spec:
  selector:
    app: mifastapi
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
  type: NodePort




---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379